version: '3.8'
services:
  proxy:
    image: huakunshen/nginx-certbot
    restart: unless-stopped
    volumes:
      - ./config:/etc/nginx/sites-available
      - ./letsencrypt:/etc/letsencrypt
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: sh /entrypoint.sh
    network_mode: 'host'
